const data = [
  {
    name: "Free Shirt",
    id: "free-shirt",
    category: "Shirts",
    image: "/images/shirt1.jpg",
    price: 700,
    brand: "Nike",
    ratings: 4.5,
    numReviews: 10,
    countInStock: 20,
    description: "A popular shirt",
  },
  {
    name: "Fit Shirt",
    id: "fit-shirt",
    category: "Shirts",
    image: "/images/shirt2.jpg",
    price: 1000,
    brand: "Adidas",
    ratings: 5,
    numReviews: 20,
    countInStock: 200,
    description: "Popular fit shirt",
  },
  {
    name: "Polyester Shirt",
    id: "polyester-shirt",
    category: "Shirts",
    image: "/images/shirt3.jpg",
    price: 1009,
    brand: "Reebok",
    ratings: 3.5,
    numReviews: 17,
    countInStock: 25,
    description: "Polyester shirt",
  },
  {
    name: "Free Pant",
    id: "free-pants",
    category: "Pants",
    image: "/images/pants1.jpg",
    price: 2200,
    brand: "Nike",
    ratings: 4.5,
    numReviews: 19,
    countInStock: 35,
    description: "A popular pant",
  },
  {
    name: "Golf Pants",
    id: "golf-pants",
    category: "Pants",
    image: "/images/pants2.jpg",
    price: 2999,
    brand: "Oliver",
    ratings: 4.8,
    numReviews: 19,
    countInStock: 22,
    description: "Golf pants for golfers.",
  },
  {
    name: "Magic Pants",
    id: "magic-panats",
    category: "Pants",
    image: "/images/Pants3.jpg",
    price: 2199,
    brand: "Reebok",
    ratings: 4.9,
    numReviews: 15,
    countInStock: 0,
    description: "A popular magic pants.",
  },
];

export default data;
