import Head from "next/head";
import Container from "../components/Container";
import Product from "../utils/models/Product";
import db from "../utils/db";

export default function Home({ products }) {
  return (
    <div>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container products={products} className="h-[100vh]" />
      </main>
    </div>
  );
}

// export async function getServerSideProps() {
//   const products = await Product.find({}).lean();

//   // const data = await fetch(`${process.env.URL}/api/products`);
//   // const items = await data.json();
//   // console.log(JSON.parse(JSON.stringify(data)));
//   // const items = JSON.parse(JSON.stringify(data));
//   return {
//     props: { products: products.map(db.convertDocToObj  ) },
//   };
// }

export async function getServerSideProps() {
  await db.connect();
  const products = await Product.find({}).lean();
  await db.disconnect();
  return {
    props: {
      products: products.map(db.convertDocToObj),
    },
  };
}
