import Head from "next/head";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Container from "../components/Container";

export default function Home() {
  return (
    <div>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main>

          <Container className="h-[100vh]" />
   
      </main>
      <Footer />
    </div>
  );
}
